### ISSUE TITLE
Honk button hover sticks 

### ISSUE THREAD

**Issue by Schassler** [porscheui/porsche-ui-contribution#2]
Reproduce:
Go to Car Overview (?) page
Click on honk button, located on car picture. 
Hover state sticks. 
(Also true for flash button)

The state can be ended by clicking some were else on the page.

**Comment by o-hook** [comment]
This is standard browser behaviour of :focus states if used as a link (<a>) element. This accessibility "issue" is well known and could be solved in the future by using ":focus-visible" which should give focus state only to elements when they are received without a mouse or fingertab (e.g. keyboard). See also: https://css-tricks.com/focusing-on-focus-styles/#article-header-id-5

But this feature is not well supported by now: https://caniuse.com/#search=focus-visible

So we have to live with these minor issue. Disabling focus styles is not an option.

**Comment by Schassler** [comment]
Thank you for the quick context stetting. I assume there is no further action to take?

**Comment by o-hook** [comment]
Due to the fact that the only possible, non-hacky solution (:focus-visible) is not well supported by now i would leave it like this. But this doesn't mean, that there aren't solutions to this behaviour. You can provide a JS polyfill (e.g.: https://github.com/WICG/focus-visible). But keep in mind that this is always at cost of overall site performance.
