### ISSUE TITLE
Bug / SCSS could not load fonts and iconfonts on React

### ISSUE THREAD

**Issue by SanQu** [porscheui/porsche-ui-contribution#21]
**Description**  
React fails to compile scss when I follow the installing instructions from https://ui.porsche.com/v0/react/#/introduction

**To Reproduce**  
1. Create a new React project with create-react-app `npx create-react-app myproject`
2. `cd myproject`
3. add this three lines to your `./index.scss`
```
@import "~@porsche/ui-kit-react/src/variables";
@import "~@porsche/ui-kit-react/src/common";
@import "~@porsche/ui-kit-react/src/index";
```
4. create .npmrc and include `@porsche:registry = https://porscheui.jfrog.io/porscheui/api/npm/npm/` 
5. run `yarn or npm install`
6. start the app `yarn start or npm run start`
6. You will see this error
```
Failed to compile.

./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/index.scss)
Module not found: Can't resolve './pag-iconfont/pag-iconfont.eot?iaj4st' in '/Users/*****/myproject/src'
```
**Expected behavior**  
React / Webpack should transpile scss and include all files

**Workarround**  
To get them work I have overwritten the following variables and included on top of my `./index.scss`. This will overwrite the wrong path and relate to the module path.
```
$icon-resource-base-path: "~@porsche/ui-kit-react/src/base/icon/pag-iconfont";
$font-resource-base-path: "~@porsche/ui-kit-core/src/base/font";
```

**$icon-resource-base-path** could be found in `@porsche/ui-kit-react/src/base/icon/pag-iconfont`
**$font-resource-base-path** could be found in `@porsche/ui-kit-core/src/base/font/font.setup.scss`

**Test Device:**  
 - Device: MacBook, Desktop
 - OS: OSX
 - Framework: React (Version 16.8.6), react-scripts (Version 3.0.1)

**Comment by o-hook** [comment]
Hi @SanQu ,
thanks for pointing out this issue. There might some unresolved issues since v3 of create-react-app regarding to compiling local scss imports which leads to break the build (see also https://github.com/facebook/create-react-app/issues/6866). 
I've checked the paths to the icon-font files and they are correct.

So the best way to solve this issue is taking your approach and overwrite the scss variable like in your example with: `$icon-resource-base-path: "~@porsche/ui-kit-react/src/base/icon/pag-iconfont";`

Since UI Kit version 0.13.0 you just need to adapt the path to the icon font because Porsche Next font is now delivered via CDN. I've updated the docs with your solution. 

If you have any better approaches to solve this bug, please let me know and we will fix it.
Thanks, Oliver

**Comment by o-hook** [comment]
Close this issue because since v0.14.x Icon Fonts are switched to SVG Icons. @see CHANGELOG for migration path.
